fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    concat: "git://github.com/puppetlabs/puppetlabs-concat.git"
    augeasproviders_core: "git://github.com/hercules-team/augeasproviders_core.git"
    augeasproviders_shellvar: "git://github.com/hercules-team/augeasproviders_shellvar.git"
    augeas_core:
      repo: "git://github.com/puppetlabs/puppetlabs-augeas_core.git"
      puppet_version: ">= 6.0.0"
    mount_core:
      repo: "git://github.com/puppetlabs/puppetlabs-mount_core.git"
      puppet_version: ">= 6.0.0"
    transition: "git://github.com/puppetlabs/puppetlabs-transition.git"
  symlinks:
    "nfs": "#{source_dir}"
